
spring:
  application:
    name: spring-webflux-ecommerce

  # Cassandra configuration
  data:
    cassandra:
      keyspace-name: your_keyspace_name
      contact-points: your_cassandra_contact_points
      username: your_username
      password: your_password

  # Kafka configuration
  kafka:
    bootstrap-servers: your_kafka_bootstrap_servers

# Memcached configuration
memcached:
  servers: your_memcached_servers
  protocol: binary

# Resilience4j configuration
resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: 60
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: PT1M
        slowCallDurationThreshold: PT2S
        minimumNumberOfCalls: 10

# Prometheus configuration
management:
  endpoints:
    web:
      exposure:
        include: 'prometheus,info,health'
  metrics:
    export:
      prometheus:
        enabled: true

# Placeholder for Google Stackdriver, Grafana, and other configurations

